all:
  hosts:
    host1:
      ansible_host: 192.168.1.10
      ansible_user: admin
      ansible_ssh_private_key_file: /path/to/private/key1.pem
      http_port: 80

    host2:
      ansible_host: 192.168.1.11
      ansible_user: admin
      ansible_ssh_private_key_file: /path/to/private/key2.pem
      http_port: 80

    host3:
      ansible_host: 192.168.1.20
      ansible_user: admin
      ansible_ssh_private_key_file: /path/to/private/key3.pem
      db_port: 5432

    host4:
      ansible_host: 192.168.1.21
      ansible_user: admin
      ansible_ssh_private_key_file: /path/to/private/key4.pem
      db_port: 5432

  children:
    webservers:
      hosts:
        host1:
        host2:

    dbservers:
      hosts:
        host3:
        host4:

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'