- name: Set root directory permissions
  file:
    path: /root
    mode: 0755
- name: Set home directory permissions
  file:
    path: /home
    mode: 0755
- name: Set system files permissions
  file:
    path: /etc/passwd
    mode: 0644
  delegate_to: localhost
- name: Set system files permissions
  file:
    path: /etc/shadow
    mode: 0640
  delegate_to: localhost 
